const loginUrl='login';
const registerUrl='register';
const updateProfile='update-profile';
const homeUrl='home';
const get_gategory='categories';
const FAVORITES = 'favorites';
const searchUrl='products/search';
const userProfile='profile';
const cartsUrl='carts';